### ISSUE TITLE
build failed？

### ISSUE THREAD

**Issue by IgNit3R** [drweissbrot/csgo-hud#44]
An error happened
Maybe only me in this trouble？

PS D:\csgodemocache\csgo-hud-master> yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@electron-forge/plugin-webpack > webpack-dev-server > http-proxy-middleware@2.0.2" has unmet peer dependency "@types/express@^4.17.13".
warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > stylus-loader@6.2.0" has unmet peer dependency "webpack@^5.0.0".
warning " > svg-url-loader@7.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > vue-loader@15.9.8" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.8" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
[4/4] Building fresh packages...
[1/3] ⠠ lzma-native
[-/3] ⠠ waiting...
error D:\csgodemocache\csgo-hud-master\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\csgodemocache\csgo-hud-master\node_modules\electron
Output:
RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\csgodemocache\csgo-hud-master\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (D:\csgodemocache\csgo-hud-master\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)

**Comment by drweissbrot** [comment]
```
RequestError: unable to verify the first certificate
```

Looks like a download is failing because of a broken certificate chain, preventing electron from getting set up.

If you're in China, this might help: https://github.com/electron/electron/issues/26910#issuecomment-762052533
If not, you'd probably have to have a look at your Windows certificate store, and see if you can maybe update it. I can't help you on that side unfortunately.

**Comment by IgNit3R** [comment]
seems like certificate chain issue
thx
